includes:
  - configs/tsc/base.yml

model:
  name: ecolight
  train_model: True
  epsilon: 0.1
  one_hot: True
  phase: True

  batch_size: 32
  tau: 0.1
  gamma: 0.9
  learning_rate: 0.001

world:
  phase_2_passable_lane_idx: {
    12: [
          [1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0],
          [1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0],
          [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1],
          [1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
          [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0],
          [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1],
          [1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0],
          [1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
        ],
    9: [
          [1, 1, 0, 1, 1, 0, 1, 0, 0],
          [1, 1, 0, 1, 0, 0, 1, 1, 0],
          [1, 0, 0, 1, 1, 1, 1, 0, 0],
          [1, 0, 1, 1, 0, 0, 1, 0, 1],
          [1, 0, 0, 1, 1, 0, 1, 1, 0],
          [1, 0, 0, 1, 1, 1, 1, 0, 0],
          [1, 0, 0, 1, 0, 0, 1, 1, 1],
          [1, 1, 1, 1, 0, 0, 1, 0, 0],
        ],
    6: [
          [1, 1, 0, 1, 1, 0],
          [1, 1, 0, 1, 1, 0],
          [1, 0, 1, 1, 0, 1],
          [1, 0, 1, 1, 0, 1],
          [1, 1, 1, 1, 0, 0],
          [1, 0, 0, 1, 1, 1],
          [1, 0, 0, 1, 1, 1],
          [1, 1, 1, 1, 0, 0],
    ]
  }
  12: 
  

trainer:
  buffer_size: 100000
  # learning_start: 32