includes:
  - configs/tsc/base.yml


model:
  name: presslight
  train_model: True
  d_dense: 20
  epsilon: 0.1
  epsilon_decay: 0.995
  epsilon_min: 0.01
  one_hot: True
  phase: True
  reward_list: ['pressure']
  
trainer:
  learning_start: 500
  buffer_size: 5000
